#!/usr/bin/env node

var messenger = require('/usr/local/lib/node_modules/messenger');
var client = messenger.createSpeaker('127.0.0.1:20001');

var projectPath = null,
    subdomain = null;

if (process.argv[2]) {
    projectPath = process.argv[2];
}

if (process.argv[3]) {
    subdomain = process.argv[3];
}

if (!projectPath) {
    throw 'A project path must be specified.';
}

if (!subdomain) {
    throw 'A subdomain must be specified.';
}

setTimeout(function() {
    console.log('Notifying Express');
    client.request('load_project', {
        'project_path': projectPath,
        'subdomain': subdomain
    }, function(data) {
        console.log('Message sent');
        process.exit(0);
    });
}, 1000);
